<?xml version="1.0" ?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-1-g15f4949  Build Version: 1.6.7594.29634
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->
<robot name="fs"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Vehicle Mass-->
  <xacro:property name="Chassis_mass" value="140"/>
  <xacro:property name="Steering_assembly_mass" value="0.001"/>
  <!-- TODO: The actual value of Wheel_mass is 10. It was set to 1.5 to stop it from wobbling  -->
  <xacro:property name="Wheel_mass" value="1.5"/>
  <xacro:property name="camera_mass" value="0.005"/>

  <xacro:include filename="$(find fs_description)/sensors/single_camera.urdf.xacro" />

  <!-- Base link -->
  <xacro:property name="base_link_length" value="0.01"/>
  <xacro:property name="base_link_width" value="0.01"/>
  <xacro:property name="base_link_height" value="0.01"/>
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
      </geometry>
    </visual>
  </link>

  <!-- Chassis START-->
  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint>

  <link name="chassis">
    <inertial>
      <origin rpy="0 0 0" xyz="-1.5 0 0.2"/>
      <mass value="${Chassis_mass}"/>
      <inertia ixx="20.536" ixy="0.006315" ixz="4.6455" iyy="109.9" iyz="-0.0023792" izz="119.33"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="-1.5 0 0.2"/>
      <geometry>
        <mesh filename="file://$(find fs_description)/meshes/ads-dv.dae"/>
      </geometry>
      <material name="">
        <color rgba="0 0.21569 0.062745 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="-1.5 0 0.2"/>
      <geometry>
        <mesh filename="file://$(find fs_description)/meshes/ads-dv.dae"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="Chassis">
    <!--Stiffness -->
    <kp>1000000.0</kp>
    <!--Dampening-->
    <kd>0.1</kd>
    <dampingFactor>0</dampingFactor>
    <material>Gazebo/White</material>
    <selfCollide>true</selfCollide>
    <turnGravityOff>false</turnGravityOff>
    <mu1 value="0.1"/>
    <mu2 value="0.1"/>
    <fdir1 value="0 0 0"/>
  </gazebo>
  <!-- Chassis END -->

  <!-- ================================= RIGHT FRONT ASSEMBLY  ================================ -->
  <link name="FR_Wheel">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.042708 0 5.5511E-17"/>
      <mass value="${Wheel_mass}"/>
      <inertia ixx="0.4246" ixy="-1.0253E-18" ixz="3.6932E-19" iyy="0.24902" iyz="-2.6847E-18" izz="0.24902"/>
      <!--<inertia ixx="0.23" ixy="0" ixz="0" iyy="0.23" iyz="0" izz="0.4"/>-->
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find fs_description)/meshes/wheel_right.dae"/>
      </geometry>
      <material name="">
        <color rgba="0 0 0.50196 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 1.5708" xyz="-0.02 0 0"/>
      <geometry>
        <cylinder length="0.15" radius="0.25"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="FR_Wheel">
    <mu1 value="2.0"/>
    <mu2 value="2.0"/>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
    <fdir1 value="0 1 0"/>
    <material>Gazebo/Black</material>
  </gazebo>

  <link name="FR_Wheel_Steer">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.101 2.7756E-17 0"/>
      <mass value="${Steering_assembly_mass}"/>
      <inertia ixx="0.00157" ixy="3.1038E-37" ixz="-4.4532E-37" iyy="0.00078756" iyz="-6.074E-39" izz="0.00078756"/>
      <!--<inertia ixx="0.23" ixy="0" ixz="0" iyy="0.23" iyz="0" izz="0.4"/>-->
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.001" radius="0.1"/>
      </geometry>
      <material name="">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="1.5708 0 1.5708" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.001" radius="0.1"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="FR_Wheel_Steer">
    <mu1 value="2.0"/>
    <mu2 value="2.0"/>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
    <fdir1 value="0 1 0"/>
    <material>Gazebo/White</material>
  </gazebo>

  <joint name="FR_hinge" type="revolute">
    <origin rpy="1.5708 0 0" xyz="-0.75017 -0.6005 0.203"/>
    <parent link="chassis"/>
    <child link="FR_Wheel_Steer"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" lower="-0.5" upper="0.5" velocity="1"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <joint name="FR_rotate" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="FR_Wheel_Steer"/>
    <child link="FR_Wheel"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <limit effort="100" velocity="50"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <transmission name="trans_right_wheel_hinge">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="FR_hinge">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_right_wheel_front">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="trans_right_wheel_rotate">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="FR_rotate">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_right_wheel_rotate">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <!-- ================================= LEFT FRONT ASSEMBLY  ================================ -->
  <link name="FL_Wheel">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.042708 0 -5.5511E-17"/>
      <mass value="${Wheel_mass}"/>
      <inertia ixx="0.4246" ixy="-3.8222E-18" ixz="-2.657E-18" iyy="0.24902" iyz="-1.1834E-18" izz="0.24902"/>
      <!--<inertia ixx="0.23" ixy="0" ixz="0" iyy="0.23" iyz="0" izz="0.4"/>-->
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find fs_description)/meshes/wheel_left.dae"/>
      </geometry>
      <material name="">
        <color rgba="0 0 0.50196 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 1.5708" xyz="-0.02 0 0"/>
      <geometry>
        <cylinder length="0.15" radius="0.25"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="FL_Wheel">
    <mu1 value="2.0"/>
    <mu2 value="2.0"/>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
    <fdir1 value="0 1 0"/>
    <material>Gazebo/Black</material>
  </gazebo>

  <link name="FL_Wheel_Steer">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.101 1.1102E-16 -1.6653E-16"/>
      <mass value="${Steering_assembly_mass}"/>
      <inertia ixx="0.00157" ixy="3.1038E-37" ixz="-4.4532E-37" iyy="0.00078756" iyz="-6.074E-39" izz="0.00078756"/>
      <!--<inertia ixx="0.23" ixy="0" ixz="0" iyy="0.23" iyz="0" izz="0.4"/>-->
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.001" radius="0.1"/>
      </geometry>
      <material name="">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="1.5708 0 1.5708" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.001" radius="0.1"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="FL_Wheel_Steer">
    <mu1 value="2.0"/>
    <mu2 value="2.0"/>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
    <fdir1 value="0 1 0"/>
    <material>Gazebo/White</material>
  </gazebo>

  <joint name="FL_hinge" type="revolute">
    <origin rpy="1.5708 0 0" xyz="-0.75017 0.6005 0.203"/>
    <parent link="chassis"/>
    <child link="FL_Wheel_Steer"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" lower="-0.5" upper="0.5" velocity="1"/>
  </joint>

  <joint name="FL_rotate" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="FL_Wheel_Steer"/>
    <child link="FL_Wheel"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <transmission name="trans_left_wheel_hing">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="FL_hinge">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_left_wheel_front">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="trans_left_wheel_rotate">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="FL_rotate">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_left_wheel_rotate">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- ================================= RIGHT WHEEL REAR ================================ -->
  <link name="RR_Wheel">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.043684 -2.7756E-17 0"/>
      <mass value="${Wheel_mass}"/>
      <inertia ixx="0.42617" ixy="-2.1805E-18" ixz="-1.5663E-17" iyy="0.25083" iyz="4.6781E-18" izz="0.25083"/>
    </inertial>
    <visual>
      <origin rpy="0 0 -1.5708" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find fs_description)/meshes/wheel_right.dae"/>
      </geometry>
      <material name="">
        <color rgba="0 0 0.50196 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 1.5708" xyz="0 0.02 0"/>
      <geometry>
        <cylinder length="0.15" radius="0.25"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="RR_Wheel">
    <mu1 value="2.0"/>
    <mu2 value="2.0"/>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
    <fdir1 value="0 1 0"/>
    <material>Gazebo/Black</material>
  </gazebo>
  <joint name="RR_rotate" type="continuous">
    <parent link="chassis"/>
    <child link="RR_Wheel"/>
    <origin rpy="-1.5708 0 0" xyz="-2.28017 -0.6005 0.2"/>
    <!-- <origin rpy="0 0 0" xyz="-0.8765 -0.8115 1.292"/> -->
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <limit effort="0" velocity="0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <!-- ================================= LEFT WHEEL REAR ================================ -->
  <link name="RL_Wheel">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.043684 5.5511E-17 -6.6613E-16"/>
      <mass value="${Wheel_mass}"/>
      <inertia ixx="0.42617" ixy="8.1301E-18" ixz="1.5197E-17" iyy="0.25083" iyz="1.5428E-17" izz="0.25083"/>
    </inertial>
    <visual>
      <origin rpy="0 0 1.5708" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find fs_description)/meshes/wheel_left.dae"/>
      </geometry>
      <material name="">
        <color rgba="0 0 0.50196 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 1.5708" xyz="0 -0.02 0"/>
      <geometry>
        <cylinder length="0.15" radius="0.25"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="RL_Wheel">
    <mu1 value="2.0"/>
    <mu2 value="2.0"/>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
    <fdir1 value="0 1 0"/>
    <material>Gazebo/Black</material>
  </gazebo>
  <joint name="RL_rotate" type="continuous">
    <parent link="chassis"/>
    <child link="RL_Wheel"/>
    <origin rpy="-1.5708 0 0" xyz="-2.28017 0.6005 0.2"/>
    <!-- <origin rpy="0 0 0" xyz="-0.8765 0.8115 1.292"/> -->
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <limit effort="0" velocity="0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- =========================================== OTHER ======================================== -->

  <!-- <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/ack</robotNamespace>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo> -->


  <!-- ========================================== CAMERA =========================================== -->
  <!-- Camera -->
  <!-- You can adjust the camera angle with the p in rpy, measured in radians. -->
  <!-- You can also increate the height of the camera by adding a number, in meters, -->
  <!-- to the z in xyz. For example, to simulate a camera mounted on a 1/2 meter post, -->
  <!-- we can replace the z value with ${wheelRadius+chassisHeight+0.5} -->

  <xacro:single_camera name="camera0" fov="1.8962634" camera_mass="${camera_mass}">
    <origin rpy="0 0.4 0.4" xyz="0 0.1 0.692" />
  </xacro:single_camera>
  <xacro:single_camera name="camera1" fov="1.8962634" camera_mass="${camera_mass}">
    <origin rpy="0 0.4 0" xyz="0 0 0.692"/>
  </xacro:single_camera>
  <xacro:single_camera name="camera2" fov="1.8962634" camera_mass="${camera_mass}">
    <origin rpy="0 0.4 -0.4" xyz="0 -0.1 0.692" />
  </xacro:single_camera>
  <xacro:single_camera name="camera_3pv" camera_mass="${camera_mass}">
    <origin xyz="-3.5 0 2.5" rpy="0 0.4 0" />
  </xacro:single_camera>

  <gazebo>
    <plugin filename="libgazebo_ros_ackermann_drive.so" name="ackermann_drive">

      <ros>
        <namespace>car</namespace>
        <remapping>cmd_vel:=cmd</remapping>
        <remapping>odom:=odom</remapping>
        <remapping>distance:=distance</remapping>
      </ros>

      <update_rate>100.0</update_rate>

      <!-- wheels -->
      <front_left_joint>FL_rotate</front_left_joint>
      <front_right_joint>FR_rotate</front_right_joint>
      <rear_left_joint>RL_rotate</rear_left_joint>
      <rear_right_joint>RR_rotate</rear_right_joint>
      <left_steering_joint>FL_hinge</left_steering_joint>
      <right_steering_joint>FR_hinge</right_steering_joint>
      <!-- <steering_wheel_joint>steering_joint</steering_wheel_joint> -->

      <!-- Max absolute steer angle for tyre in radians-->
      <!-- Any cmd_vel angular z greater than this would be capped -->
      <max_steer>0.658</max_steer>

      <!-- Max absolute steering angle of steering wheel -->
      <max_steering_angle>7.85</max_steering_angle>

      <!-- Max absolute linear speed in m/s -->
      <max_speed>10</max_speed>

      <!-- PID tuning -->
      <left_steering_pid_gain>292.28 0 1</left_steering_pid_gain>
      <left_steering_i_range>0 0</left_steering_i_range>
      <right_steering_pid_gain>292.28 0 1</right_steering_pid_gain>
      <right_steering_i_range>0 0</right_steering_i_range>
      <linear_velocity_pid_gain>140 0 0.1143</linear_velocity_pid_gain>
      <linear_velocity_i_range>0 0</linear_velocity_i_range>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <publish_distance>true</publish_distance>

      <odometry_frame>odom_frame</odometry_frame>
      <robot_base_frame>chassis</robot_base_frame>

    </plugin>
  </gazebo>

</robot>

